version: '3.7'

services:
  profilesdashboard-db:
    build:
      context: ./dbBackup
    volumes:
      - ./backups:/backups
    environment:
      - TZ=America/Sao_Paulo
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - gateway-shared-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5


  django_profiledashboard:
    build: .
    command: sh -c "python manage.py migrate && python manage.py create_all_mv && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    environment:
      - DB_HOST=profilesdashboard-db
      - DB_NAME=${POSTGRES_DB}
      - DB_ENGINE=django.db.backends.postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=${POSTGRES_USER}
      - DB_PORT=${DB_PORT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

    ports:
      - 8000:8000
    volumes:
      - .:/profileAuth
    depends_on:
      - profilesdashboard-db
    networks:
      - gateway-shared-net
      - rabbit-MQ-extern-network
    
    
  rabbitMQ-profile-events:
    image: rabbitmq:3-management
    container_name: rabbit-dashboard
    hostname: rabbit-dash
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gateway-shared-net
      - rabbit-MQ-extern-network
networks:
  gateway-shared-net:
    external: true
  rabbit-MQ-extern-network:
    external: true
