# pyproject.toml
[tool.black]
line-length = 88 # Ou o mesmo que você usa no Flake8 para max-line-length
target-version = ['py39'] # Ajuste para a versão do seu Python (ex: py38, py39, py310)
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | venv
  | _build
  | buck-out
  | build
  | dist
  | .manage.py
  | migrations # <--- Adicione 'migrations' aqui!
)/
'''