# Generated by Django 5.2.1 on 2025-05-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileCore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardprofile',
            name='username',
        ),
    ]
