# Generated by Django 5.2.1 on 2025-05-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileCore', '0002_remove_dashboardprofile_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dashboardprofile',
            managers=[
            ],
        ),
    ]
