# Generated by Django 5.2.1 on 2025-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileCore', '0005_alter_dashboardprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weigthhistory',
            name='imc_on_date',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
