# Generated by Django 5.2.1 on 2025-07-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileCore', '0006_weigthhistory_imc_on_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weigthhistory',
            options={'ordering': ['-created_at']},
        ),
    ]
