# Generated by Django 5.2.1 on 2025-07-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileCore", "0007_alter_weigthhistory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthWeigth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weigth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "imc_on_date",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "mv_weigth_history_monthly_mv",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
