# Generated by Django 5.2.1 on 2025-08-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileCore", "0008_monthweigth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboardprofile",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="dashboardprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="dashboardprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="historicaldashboardprofile",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="historicaldashboardprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="historicaldashboardprofile",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="dashboardprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="dashboardprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="dashboardprofile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicaldashboardprofile",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="historicaldashboardprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicaldashboardprofile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
