FROM postgres:17.5
RUN apt-get update && apt-get install -y cron procps
COPY backup_script.sh /docker-entrypoint-initdb.d/backup_script.sh
COPY start.sh /start.sh
RUN chmod +x /start.sh
RUN chmod +x /docker-entrypoint-initdb.d/backup_script.sh
CMD ["/start.sh"]