name: CD - Deploy para produção

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{secrets.EC2_USER}}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: RABBITMQ_DEFAULT_PORT,DEBUG,DB_HOST,DB_NAME,DB_USER,DB_PASSWORD,DB_PORT,RABBITMQ_DEFAULT_USER,RABBITMQ_DEFAULT_PASS,RABBITMQ_DEFAULT_VHOST,ALLOWED_HOSTS,DB_ENGINE
          script: |
            cd /home/ubuntu/repos/ProfileAuthDashboard
            git pull origin main

            export "DB_ENGINE=django.db.backends.postgresql" > .env.prod \
            export "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}"  > .env.prod \
            export "DB_HOST=${{ secrets.DB_HOST }}"  > .env.prod \
            export "POSTGRES_HOST=${{ secrets.DB_HOST }}"  > .env.prod \

            export "DB_NAME=${{ secrets.DB_NAME }}"  > .env.prod \
            export "POSTGRES_DB=${{ secrets.DB_NAME }}"  > .env.prod \

            export "DB_USER=${{ secrets.DB_USER }}"  > .env.prod \
            export "POSTGRES_USER=${{ secrets.DB_USER }}"  > .env.prod \

            export "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"  > .env.prod \
            export "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}"  > .env.prod \
            
            export "DB_PORT=${{ secrets.DB_PORT }}"  > .env.prod \
            export "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"  > .env.prod \
            export "SECRETJWT=${{ secrets.SECRETJWT }}"  > .env.prod \
            export "ACCESS_TIME=${{ secrets.ACCESS_TIME }}"  > .env.prod \
            export "REFRESH_TIME=${{ secrets.REFRESH_TIME }}"  > .env.prod \
            export "RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }}"  > .env.prod \
            export "RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS }}"  > .env.prod \
            export "RABBITMQ_DEFAULT_VHOST=${{ secrets.RABBITMQ_DEFAULT_VHOST }}"  > .env.prod \
            export "RABBITMQ_DEFAULT_PORT=${{secrets.RABBITMQ_DEFAULT_PORT}}"  > .env.prod \
            export "DEBUG=${{secrets.DEBUG}}"  > .env.prod

            docker-compose -f docker-compose.prod.yml up -d --build
            cat .env.prod