name: CD - Deploy para produção

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{secrets.EC2_USER}}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DB_HOST,DB_NAME,DB_USER,DB_PASSWORD,DB_PORT,RABBITMQ_DEFAULT_USER,RABBITMQ_DEFAULT_PASS,RABBITMQ_DEFAULT_VHOST,ALLOWED_HOSTS,DB_ENGINE
          script: |
            cd /home/ubuntu/repos/ProfileAuthDashboard
            git pull origin main

            export DB_ENGINE=django.db.backends.postgresql \
            export ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} \
            export DB_HOST=${{ secrets.DB_HOST }} \
            export POSTGRES_HOST=${{ secrets.DB_HOST }} \

            export DB_NAME=${{ secrets.DB_NAME }} \
            export POSTGRES_DB=${{ secrets.DB_NAME }} \

            export DB_USER=${{ secrets.DB_USER }} \
            export POSTGRES_USER=${{ secrets.DB_USER }} \

            export DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            export POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
            
            export DB_PORT=${{ secrets.DB_PORT }} \
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            export SECRETJWT=${{ secrets.SECRETJWT }} \
            export ACCESS_TIME=${{ secrets.ACCESS_TIME }} \
            export REFRESH_TIME=${{ secrets.REFRESH_TIME }} \
            export RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }} \
            export RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS }} \
            export RABBITMQ_DEFAULT_VHOST=${{ secrets.RABBITMQ_DEFAULT_VHOST }} \

            docker-compose -f docker-compose.prod.yml up -d --build