name: CD - Deploy para produção

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{secrets.EC2_USER}}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: |
            DB_ENGINE,
            ALLOWED_HOSTS,
            DB_HOST,
            DB_NAME,
            DB_USER,
            DB_PASSWORD,
            DB_PORT,
            GOOGLE_CLIENT_ID,
            SECRETJWT,
            ACCESS_TIME,
            REFRESH_TIME,
            RABBITMQ_DEFAULT_USER,
            RABBITMQ_DEFAULT_PASS,
            RABBITMQ_DEFAULT_VHOST,
            RABBITMQ_DEFAULT_PORT,
            RABBITMQ_QUEUE_NAME,
            RABBITMQ_EXCHANGE_NAME,
            RABBITMQ_EXCHANGE_TYPE,
            DEBUG
          script: |
            cd /home/ubuntu/repos/ProfileAuthDashboard
            git pull origin main

            echo "DB_ENGINE=$DB_ENGINE" > .env.prod
            echo "ALLOWED_HOSTS=$ALLOWED_HOSTS" >> .env.prod
            echo "DB_HOST=$DB_HOST" >> .env.prod
            echo "POSTGRES_HOST=$DB_HOST" >> .env.prod
            echo "DB_NAME=$DB_NAME" >> .env.prod
            echo "POSTGRES_DB=$DB_NAME" >> .env.prod
            echo "DB_USER=$DB_USER" >> .env.prod
            echo "POSTGRES_USER=$DB_USER" >> .env.prod
            echo "DB_PASSWORD=$DB_PASSWORD" >> .env.prod
            echo "POSTGRES_PASSWORD=$DB_PASSWORD" >> .env.prod
            echo "DB_PORT=$DB_PORT" >> .env.prod
            echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env.prod
            echo "SECRETJWT=$SECRETJWT" >> .env.prod
            echo "ACCESS_TIME=$ACCESS_TIME" >> .env.prod
            echo "REFRESH_TIME=$REFRESH_TIME" >> .env.prod
            echo "RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER" >> .env.prod
            echo "RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS" >> .env.prod
            echo "RABBITMQ_DEFAULT_VHOST=$RABBITMQ_DEFAULT_VHOST" >> .env.prod
            echo "RABBITMQ_DEFAULT_PORT=$RABBITMQ_DEFAULT_PORT" >> .env.prod
            echo "RABBITMQ_QUEUE_NAME=$RABBITMQ_QUEUE_NAME" >> .env.prod
            echo "RABBITMQ_EXCHANGE_NAME=$RABBITMQ_EXCHANGE_NAME" >> .env.prod
            echo "RABBITMQ_EXCHANGE_TYPE=$RABBITMQ_EXCHANGE_TYPE" >> .env.prod
            echo "DEBUG=$DEBUG" >> .env.prod

            docker-compose -f docker-compose.prod.yml --env-file .env.prod up -d --build
            cat .env.prod

    



