name: CD - Deploy para produção

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{secrets.EC2_USER}}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/repos/ProfileAuthDashboard
            git pull origin main

            echo "DB_ENGINE=django.db.backends.postgresql" > .env.prod 
            echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}"  >> .env.prod 
            echo "DB_HOST=${{ secrets.DB_HOST }}"  >> .env.prod 
            echo "POSTGRES_HOST=${{ secrets.DB_HOST }}"  >> .env.prod 

            echo "DB_NAME=${{ secrets.DB_NAME }}"  >> .env.prod 
            echo "POSTGRES_DB=${{ secrets.DB_NAME }}"  >> .env.prod 

            echo "DB_USER=${{ secrets.DB_USER }}"  >> .env.prod 
            echo "POSTGRES_USER=${{ secrets.DB_USER }}"  >> .env.prod 

            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"  >> .env.prod 
            echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}"  >> .env.prod 
            
            echo "DB_PORT=${{ secrets.DB_PORT }}"  >> .env.prod 
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"  >> .env.prod 
            echo "SECRETJWT=${{ secrets.SECRETJWT }}"  >> .env.prod 
            echo "ACCESS_TIME=${{ secrets.ACCESS_TIME }}"  >> .env.prod 
            echo "REFRESH_TIME=${{ secrets.REFRESH_TIME }}"  >> .env.prod 
            echo "RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }}"  >> .env.prod 
            echo "RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS }}"  >> .env.prod 
            echo "RABBITMQ_DEFAULT_VHOST=${{ secrets.RABBITMQ_DEFAULT_VHOST }}"  >> .env.prod 
            echo "RABBITMQ_DEFAULT_PORT=${{secrets.RABBITMQ_DEFAULT_PORT}}"  >> .env.prod 
            echo "RABBITMQ_QUEUE_NAME=${{secrets.RABBITMQ_QUEUE_NAME}}" >> .env.prod
            echo "DEBUG=${{secrets.DEBUG}}"  >> .env.prod
            echo "RABBITMQ_EXCHANGE_NAME=${{secrets.RABBITMQ_EXCHANGE_NAME}}" >> .env.prod
            echo "RABBITMQ_EXCHANGE_TYPE=${{secrets.RABBITMQ_EXCHANGE_TYPE}}" >> .env.prod
            echo "RABBITMQ_DEFAULT_HOST=${{secrets.RABBITMQ_DEFAULT_HOST}}" >> .env.prod

            docker-compose -f docker-compose.prod.yml --env-file .env.prod up -d --build